"""Browser regression suite (not run by unittest discover).

Start a server on a *copy* of the db, then run this with a Python that has Playwright:

    cp data/todo.db /tmp/ui.db && python3 server.py --db /tmp/ui.db --port 5799 &
    ~/.venvs/ml/bin/python tests/ui_playwright.py

It types into the page like a user would and checks the API after each keystroke.
"""
import asyncio, json, os, sys, urllib.request
from playwright.async_api import async_playwright
import os, tempfile
SP = os.environ.get('UI_SHOTS', tempfile.gettempdir())  # where screenshots go
URL = f"http://127.0.0.1:{os.environ.get('UI_PORT', '5799')}/"
def tree():
    nodes = json.load(urllib.request.urlopen(URL + 'api/tree'))['nodes']
    return {n['id']: n for n in nodes}
def by_text(t, text):
    return next(n for n in t.values() if n['text'] == text)
checks = []
def check(name, cond, detail=''):
    checks.append((name, bool(cond))); print(('PASS ' if cond else 'FAIL ') + name + (f'  [{detail}]' if detail and not cond else ''))

async def main():
    async with async_playwright() as p:
        b = await getattr(p, os.environ.get('BROWSER', 'chromium')).launch()
        pg = await b.new_page(viewport={'width': 1100, 'height': 1300})  # tall enough that drags do not scroll mid-way at 140%
        pg.set_default_timeout(8000)
        errors = []
        pg.on('console', lambda m: errors.append(f'{m.type}: {m.text}') if m.type in ('error', 'warning') else None)
        pg.on('pageerror', lambda e: (errors.append(f'pageerror: {e}'), logs.append(f'PAGEERROR {e}\n{e.stack}')))
        await pg.goto(URL); await pg.wait_for_selector('.node')
        logs = []; pg.on('console', lambda m: logs.append(f'{m.type}: {m.text}'))
        await pg.evaluate("""() => { for (const k of ['done','move','patch','split','del']) { const o = api[k]; api[k] = (...a) => { console.log('API', k, JSON.stringify(a)); return o(...a).then(r => r, e => { console.log('ERR', k, e.message); throw e; }); }; }
          document.addEventListener('change', e => console.log('CHANGE', e.target.className, e.target.checked, 'node', e.target.closest('.node')?.dataset.id), true);
          document.addEventListener('click', e => console.log('CLICK', e.target.className, 'node', e.target.closest('.node')?.dataset.id), true);
          document.addEventListener('drop', e => console.log('DROP', e.target.className), true); }""")
        await pg.screenshot(path=f'{SP}/ui-all.png')
        check('renders all nodes', await pg.locator('.node').count() == 113, await pg.locator('.node').count())
        # --- Enter splits / creates
        t = pg.locator('.node.task > .row > .text', has_text='Reach out Alex Rivera').first
        await t.click(); await pg.keyboard.press('End'); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(400)
        await pg.keyboard.type('New item via Enter'); await pg.wait_for_timeout(600)
        tr = tree(); new = by_text(tr, 'New item via Enter'); first_row = by_text(tr, 'Reach out Alex Rivera')
        check('Enter creates sibling after', new['parent_id'] == first_row['parent_id'] and new['position'] == first_row['position'] + 1)
        check('focus on new item', await pg.evaluate('document.activeElement.textContent') == 'New item via Enter')
        # --- Tab / Shift+Tab
        await pg.keyboard.press('Tab'); await pg.wait_for_timeout(400)
        check('Tab nests under previous', tree()[new['id']]['parent_id'] == first_row['id'])
        check('focus kept after Tab', await pg.evaluate('document.activeElement.textContent') == 'New item via Enter')
        await pg.keyboard.press('Shift+Tab'); await pg.wait_for_timeout(400)
        check('Shift+Tab un-nests', tree()[new['id']]['parent_id'] == first_row['parent_id'])
        # --- Alt+Up
        await pg.keyboard.press('Alt+ArrowUp'); await pg.wait_for_timeout(400)
        check('Alt+Up moves above', tree()[new['id']]['position'] == first_row['position'])
        # --- priority + done + heading toggles
        await pg.keyboard.press('Control+Shift+Digit1'); await pg.wait_for_timeout(400)
        check('Ctrl+Shift+1 = urgent', tree()[new['id']]['priority'] == 'urgent')
        check('urgent renders red', 'urgent' == await pg.evaluate(f'document.querySelector(\'.node[data-id="{new["id"]}"]\').dataset.prio'))
        await pg.keyboard.press('Control+Shift+Digit4'); await pg.wait_for_timeout(400)
        check('Ctrl+Shift+4 = later', tree()[new['id']]['priority'] == 'later')
        await pg.keyboard.press('Control+Enter'); await pg.wait_for_timeout(400)
        check('Ctrl+Enter marks done', tree()[new['id']]['done_at'])
        check('done row styled', await pg.evaluate(f'document.querySelector(\'.node[data-id="{new["id"]}"]\').classList.contains("done")'))
        await pg.keyboard.press('Control+Enter'); await pg.wait_for_timeout(400)
        check('Ctrl+Enter again un-does', not tree()[new['id']]['done_at'])
        # --- due popover
        await pg.keyboard.press('Control+d'); await pg.wait_for_timeout(300)
        check('Ctrl+D opens calendar', await pg.locator('#popover .cal-grid').is_visible())
        await pg.locator('#popover .day.today').click(); await pg.wait_for_timeout(300)
        await pg.locator('#popover .slots button', has_text='Morning').click(); await pg.wait_for_timeout(400)
        n = tree()[new['id']]
        check('calendar sets today + morning', n['due_slot'] == 'morning' and n['due_date'], (n['due_date'], n['due_slot']))
        chip = await pg.locator(f'.node[data-id="{new["id"]}"] > .row > .chip').text_content()
        check('chip shows Today · morning', chip == 'Today · morning', chip)
        await pg.screenshot(path=f'{SP}/ui-due.png')
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(200)
        check('Escape closes popover', await pg.locator('#popover').is_hidden())
        # --- heading toggle
        await pg.locator(f'.node[data-id="{new["id"]}"] > .row > .text').click()
        await pg.keyboard.press('Control+Shift+h'); await pg.wait_for_timeout(400)
        check('Ctrl+Shift+H makes heading', tree()[new['id']]['kind'] == 'heading' and tree()[new['id']]['due_date'] is None)
        await pg.keyboard.press('Control+Shift+h'); await pg.wait_for_timeout(400)
        check('… and back to task', tree()[new['id']]['kind'] == 'task')
        # --- Enter mid-text splits
        await pg.locator(f'.node[data-id="{new["id"]}"] > .row > .text').click()
        await pg.keyboard.press('Home'); await pg.keyboard.press('ArrowRight'); await pg.keyboard.press('ArrowRight'); await pg.keyboard.press('ArrowRight')
        await pg.keyboard.press('Enter'); await pg.wait_for_timeout(400)
        tr = tree(); check('Enter splits at caret', tr[new['id']]['text'] == 'New' and any(x['text'] == ' item via Enter' for x in tr.values()))
        tail = by_text(tr, ' item via Enter')
        # --- Backspace on empty deletes
        await pg.keyboard.press('End'); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(400)
        cnt = len(tree()); await pg.keyboard.press('Backspace'); await pg.wait_for_timeout(400)
        check('Backspace on empty deletes', len(tree()) == cnt - 1)
        check('focus returns to previous', await pg.evaluate('document.activeElement.textContent') == ' item via Enter')
        # --- arrow navigation
        await pg.keyboard.press('ArrowUp'); await pg.wait_for_timeout(100)
        check('ArrowUp moves to previous item', await pg.evaluate('document.activeElement.textContent') == 'New')
        # --- typing autosaves
        await pg.keyboard.press('End'); await pg.keyboard.type(' typed'); await pg.wait_for_timeout(700)
        check('typing autosaves', tree()[new['id']]['text'] == 'New typed')
        # --- mouse: checkbox, dot picker, menu
        logs.append('--- checkbox step, tail id ' + str(tail['id']))
        await pg.locator(f'.node[data-id="{tail["id"]}"] > .row > .check').click(); await pg.wait_for_timeout(400)
        check('checkbox marks done', tree()[tail['id']]['done_at'])
        logs.append('--- end checkbox step; tail now ' + json.dumps({k: tree()[tail['id']][k] for k in ('text','done_at','parent_id','position')}))
        await pg.locator(f'.node[data-id="{new["id"]}"] > .row > .dot').click(); await pg.wait_for_timeout(200)
        await pg.locator('#popover .swatch[data-prio=soon]').click(); await pg.wait_for_timeout(400)
        check('dot picker sets soon', tree()[new['id']]['priority'] == 'soon')
        await pg.locator(f'.node[data-id="{new["id"]}"] > .row').hover()
        await pg.locator(f'.node[data-id="{new["id"]}"] > .row > .menu').click(); await pg.wait_for_timeout(200)
        check('menu opens', await pg.locator('#popover .menu-list').is_visible())
        await pg.screenshot(path=f'{SP}/ui-menu.png')
        await pg.locator('#popover .menu-list button', has_text='Move down').click(); await pg.wait_for_timeout(400)
        check('menu move down', tree()[new['id']]['position'] == tree()[tail['id']]['position'] + 1, (tree()[new['id']]['position'], tree()[tail['id']]['position']))
        # --- Enter on a heading creates its first child
        await pg.locator('.node.heading > .row > .text', has_text='Career').first.click(); await pg.keyboard.press('End'); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(400)
        await pg.keyboard.type('first career task'); await pg.wait_for_timeout(600)
        tr = tree(); check('Enter on heading creates first child', by_text(tr, 'first career task')['parent_id'] == by_text(tr, 'Career')['id'])
        # --- fold
        fold_node = by_text(tree(), 'Reach out to ppl')
        await pg.locator(f'.node[data-id="{fold_node["id"]}"] > .row > .fold').click(); await pg.wait_for_timeout(400)
        check('fold hides children', await pg.locator(f'.node[data-id="{fold_node["id"]}"] .kids .node').count() == 0 and tree()[fold_node['id']]['collapsed'] == 1)
        await pg.locator(f'.node[data-id="{fold_node["id"]}"] > .row > .fold').click(); await pg.wait_for_timeout(400)
        check('unfold shows children', await pg.locator(f'.node[data-id="{fold_node["id"]}"] .kids .node').count() == 4)
        # --- search
        await pg.keyboard.press('Control+k'); await pg.keyboard.type('jo bell'); await pg.wait_for_timeout(400)
        check('search shows match + its ancestors only', await pg.locator('#view .node.task').count() == 2 and await pg.locator('#view .node.task > .row > .text', has_text='jo bell').count() == 1, await pg.locator('#view .node.task').count())
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(300)
        check('Escape clears search', await pg.locator('#view .node').count() > 100)
        # --- views
        await pg.click('#tabs button[data-view=today]'); await pg.wait_for_timeout(400)
        heads = await pg.locator('#view .node.heading').count(); items = await pg.locator('#view .node.task').count()
        check('Today view keeps the outline (sections + tasks)', heads >= 2 and items >= 3, (heads, items))
        sub = by_text(tree(), 'Update the Racer'); par = by_text(tree(), 'Orientation 1 time')
        urllib.request.urlopen(urllib.request.Request(URL + f'api/nodes/{sub["id"]}', data=json.dumps({'due_date': __import__('datetime').date.today().isoformat()}).encode(), method='PATCH', headers={'Content-Type': 'application/json'})).read()
        await pg.reload(); await pg.wait_for_selector('.node'); await pg.click('#tabs button[data-view=today]'); await pg.wait_for_timeout(500)
        check('Today nests a sub-task under its parent task like All', await pg.locator(f'.node[data-id="{par["id"]}"] > .kids > .node[data-id="{sub["id"]}"]').count() == 1)
        check('sections with nothing due are left out', await pg.locator('#view .node.heading > .row > .text', has_text='Career').count() == 0)
        kid2 = by_text(tree(), 'And prep it')  # sibling of the due sub-task, itself undated: comes along with its due parent
        check('every child of a due parent shows in Today', await pg.locator(f'.node[data-id="{kid2["id"]}"]').count() == 1)
        await pg.screenshot(path=f'{SP}/ui-today.png')
        await pg.click('#tabs button[data-view=done]'); await pg.wait_for_timeout(600)
        check('Done view shows the done item in its outline', await pg.locator('#view .node.done > .row > .text', has_text=' item via Enter').count() == 1 and await pg.locator('#view .node.done > .row > .when').count() >= 1)
        await pg.screenshot(path=f'{SP}/ui-done.png')
        await pg.evaluate("setView('history')"); await pg.wait_for_timeout(600)
        check('History tab is hidden until opened', await pg.locator('#tabs button[data-view=history]').is_visible())
        rows = await pg.locator('table.history tr').count()
        check('History view has rows', rows > 113, rows)
        first = await pg.locator('table.history tr').first.text_content()
        await pg.screenshot(path=f'{SP}/ui-history.png')
        await pg.click('#tabs button[data-view=all]'); await pg.wait_for_timeout(400)
        # --- hide done + archive done
        await pg.click('#hide-done'); await pg.wait_for_timeout(300)
        check('Hide done hides', await pg.locator('#view .node.done').count() == 0)
        await pg.click('#hide-done'); await pg.wait_for_timeout(300)
        await pg.click('#archive-done'); await pg.wait_for_timeout(600)
        check('Archive done removes done', all(not n['done_at'] for n in tree().values()))
        # --- drag: drag 'IROS Book' handle onto 'PhD Apps think through' row (after)
        src = by_text(tree(), 'IROS Book'); dst = by_text(tree(), 'PhD Apps think through')
        await pg.locator(f'.node[data-id="{src["id"]}"] > .row').hover()
        h = pg.locator(f'.node[data-id="{src["id"]}"] > .row > .handle'); d = pg.locator(f'.node[data-id="{dst["id"]}"] > .row')
        rh = (await d.bounding_box())['height']; check('task rows are single-line', rh < 48, rh)  # 140% scale
        logs.append('--- drag step')
        await pg.drag_and_drop(f'.node[data-id="{src["id"]}"] > .row > .handle', f'.node[data-id="{dst["id"]}"] > .row', target_position={'x': 200, 'y': rh - 4}); await pg.wait_for_timeout(500)
        check('drag reorders', tree()[src['id']]['position'] > tree()[dst['id']]['position'], (tree()[src['id']]['position'], tree()[dst['id']]['position']))
        check('status dot saved', await pg.evaluate('document.querySelector("#status").className') == 'saved')
        await pg.screenshot(path=f'{SP}/ui-final.png')
        # ================= undo / redo, robust Tab, moving between sections
        first = by_text(tree(), 'first career task')
        await pg.locator(f'.node[data-id="{first["id"]}"] > .row > .text').click(); await pg.keyboard.press('End')
        await pg.keyboard.type(' more'); await pg.wait_for_timeout(700)
        check('typed suffix saved', tree()[first['id']]['text'] == 'first career task more')
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(500)
        check('Ctrl+Z undoes typing', tree()[first['id']]['text'] == 'first career task', tree()[first['id']]['text'])
        await pg.keyboard.press('Control+y'); await pg.wait_for_timeout(500)
        check('Ctrl+Y redoes typing', tree()[first['id']]['text'] == 'first career task more')
        await pg.keyboard.press('Control+Shift+Digit1'); await pg.wait_for_timeout(300)
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(500)
        check('Ctrl+Z undoes priority', tree()[first['id']]['priority'] == 'none')
        await pg.keyboard.press('Control+Enter'); await pg.wait_for_timeout(300)
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(500)
        check('Ctrl+Z undoes done', not tree()[first['id']]['done_at'])
        await pg.locator(f'.node[data-id="{first["id"]}"] > .row > .text').click(); await pg.keyboard.press('End')
        await pg.keyboard.press('Enter'); await pg.wait_for_timeout(400); await pg.keyboard.type('second'); await pg.wait_for_timeout(700)
        second = by_text(tree(), 'second'); cnt = len(tree())
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(500)
        check('undo typing in the new item', tree()[second['id']]['text'] == '', tree()[second['id']]['text'])
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(500)
        check('undo new item removes it', len(tree()) == cnt - 1 and second['id'] not in tree())
        check('focus returns to the item above', await pg.evaluate('document.activeElement.textContent') == 'first career task more')
        await pg.keyboard.press('Control+y'); await pg.wait_for_timeout(500)
        await pg.keyboard.press('Control+y'); await pg.wait_for_timeout(500)
        tr = tree(); check('redo twice brings the item back with its text', any(x['text'] == 'second' for x in tr.values()) and len(tr) == cnt)
        second = by_text(tr, 'second')
        await pg.locator(f'.node[data-id="{second["id"]}"] > .row > .dot').click(); await pg.wait_for_timeout(200)
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(100)
        await pg.keyboard.press('Tab'); await pg.wait_for_timeout(500)
        check('Tab with focus on a button still nests', tree()[second['id']]['parent_id'] == first['id'], tree()[second['id']]['parent_id'])
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(500)
        check('Ctrl+Z undoes nesting', tree()[second['id']]['parent_id'] == first['parent_id'])
        await pg.locator(f'.node[data-id="{second["id"]}"] > .row > .text').click()
        await pg.keyboard.press('Alt+ArrowDown'); await pg.wait_for_timeout(500)
        job = by_text(tree(), 'Job Search'); career = by_text(tree(), 'Career')
        check('Alt+Down at the section end hops out below the heading', tree()[second['id']]['parent_id'] == job['id'] and tree()[second['id']]['position'] == career['position'] + 1, (tree()[second['id']]['parent_id'], job['id']))
        await pg.keyboard.press('Alt+ArrowUp'); await pg.wait_for_timeout(500)
        check('Alt+Up from below a heading hops into its end', tree()[second['id']]['parent_id'] == career['id'], tree()[second['id']]['parent_id'])
        await pg.locator(f'.node[data-id="{second["id"]}"] > .row').hover()
        await pg.locator(f'.node[data-id="{second["id"]}"] > .row > .menu').click(); await pg.wait_for_timeout(200)
        await pg.locator('#popover .menu-list button', has_text='Move to section').click(); await pg.wait_for_timeout(300)
        await pg.keyboard.type('leet'); await pg.wait_for_timeout(200); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(500)
        leet = by_text(tree(), 'Leetcode')
        check('Move to section… via menu', tree()[second['id']]['parent_id'] == leet['id'], tree()[second['id']]['parent_id'])
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(500)
        check('Ctrl+Z undoes the section move', tree()[second['id']]['parent_id'] == career['id'])
        cpp = by_text(tree(), 'Learning')  # the root section right below Job Search, so no scrolling mid-drag
        await pg.locator(f'.node[data-id="{second["id"]}"] > .row').hover()
        rh2 = (await pg.locator(f'.node[data-id="{cpp["id"]}"] > .row').bounding_box())['height']
        await pg.drag_and_drop(f'.node[data-id="{second["id"]}"] > .row > .handle', f'.node[data-id="{cpp["id"]}"] > .row', target_position={'x': 200, 'y': rh2 - 4}); await pg.wait_for_timeout(500)
        check('drop on a heading moves into it as first child', tree()[second['id']]['parent_id'] == cpp['id'] and tree()[second['id']]['position'] == 0, (tree()[second['id']]['parent_id'], tree()[second['id']]['position']))
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(500)
        check('Ctrl+Z undoes the drop', tree()[second['id']]['parent_id'] == career['id'])
        await pg.locator(f'.node[data-id="{second["id"]}"] > .row').hover()
        await pg.locator(f'.node[data-id="{second["id"]}"] > .row > .menu').click(); await pg.wait_for_timeout(200)
        await pg.locator('#popover .menu-list button', has_text='Archive').click(); await pg.wait_for_timeout(500)
        check('menu archive removes the item', second['id'] not in tree())
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(600)
        tr = tree(); check('Ctrl+Z restores the archived item in place', second['id'] in tr and tr[second['id']]['parent_id'] == career['id'] and tr[second['id']]['position'] == tr[first['id']]['position'] + 1)
        await pg.locator(f'.node[data-id="{second["id"]}"] > .row > .check').click(); await pg.wait_for_timeout(400)
        await pg.click('#archive-done'); await pg.wait_for_timeout(600)
        check('Archive done removes it', second['id'] not in tree())
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(700)
        tr = tree(); check('Ctrl+Z restores archived-done item, still done', second['id'] in tr and bool(tr[second['id']]['done_at']))
        await pg.locator(f'.node[data-id="{second["id"]}"] > .row > .text').click()
        await pg.keyboard.press('Control+/'); await pg.wait_for_timeout(300)
        check('Ctrl+/ opens the section picker', await pg.locator('#popover .section-picker').is_visible())
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(200)
        check('Escape closes it', await pg.locator('#popover').is_hidden())
        # --- sub-tasks complete their parent, and the other way round
        await pg.locator(f'.node[data-id="{second["id"]}"] > .row > .check').click(); await pg.wait_for_timeout(400)  # re-open it
        await pg.locator(f'.node[data-id="{second["id"]}"] > .row > .text').click(); await pg.keyboard.press('Tab'); await pg.wait_for_timeout(500)
        check('nested under first', tree()[second['id']]['parent_id'] == first['id'])
        await pg.locator(f'.node[data-id="{second["id"]}"] > .row > .check').click(); await pg.wait_for_timeout(600)
        tr = tree(); check('checking the only sub-task completes the parent', bool(tr[first['id']]['done_at']) and bool(tr[second['id']]['done_at']))
        check('parent row drawn as done', 'done' in (await pg.locator(f'.node[data-id="{first["id"]}"]').get_attribute('class')))
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(600)
        tr = tree(); check('Ctrl+Z reopens both', not tr[first['id']]['done_at'] and not tr[second['id']]['done_at'])
        await pg.locator(f'.node[data-id="{first["id"]}"] > .row > .check').click(); await pg.wait_for_timeout(600)
        tr = tree(); check('checking the parent completes its sub-task', bool(tr[first['id']]['done_at']) and bool(tr[second['id']]['done_at']))
        await pg.locator(f'.node[data-id="{second["id"]}"] > .row > .check').click(); await pg.wait_for_timeout(600)
        tr = tree(); check('re-opening the sub-task re-opens the parent', not tr[first['id']]['done_at'] and not tr[second['id']]['done_at'])
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(600)
        tr = tree(); check('Ctrl+Z puts both back to done', bool(tr[first['id']]['done_at']) and bool(tr[second['id']]['done_at']))
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(600)
        tr = tree(); check('another Ctrl+Z reopens both again', not tr[first['id']]['done_at'] and not tr[second['id']]['done_at'])
        # --- waiting on someone
        await pg.locator(f'.node[data-id="{first["id"]}"] > .row > .text').click()
        await pg.keyboard.press('Control+b'); await pg.wait_for_timeout(300)
        check('Ctrl+B opens the waiting picker', await pg.locator('#popover .wait-picker').is_visible())
        await pg.keyboard.type('Sam: which channel'); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(600)
        tr = tree(); check('waiting_on saved with a since stamp', tr[first['id']]['waiting_on'] == 'Sam: which channel' and bool(tr[first['id']]['waiting_since']))
        check('row is marked waiting', 'waiting' in (await pg.locator(f'.node[data-id="{first["id"]}"]').get_attribute('class')))
        check('chip names who and how long', 'Sam' in await pg.locator(f'.node[data-id="{first["id"]}"] > .row > .wait').text_content() and 'today' in await pg.locator(f'.node[data-id="{first["id"]}"] > .row > .wait').text_content())
        check('still an open todo', not tr[first['id']]['done_at'])
        await pg.click('#tabs button[data-view=waiting]'); await pg.wait_for_timeout(300)
        check('Waiting tab shows it under its section, outline style', await pg.locator('#view .node.task').count() == 1 and await pg.locator('#view .node.heading > .row > .text', has_text='Career').count() == 1)
        await pg.locator('#view .node > .row > .wait').click(); await pg.wait_for_timeout(200)
        await pg.locator('#popover .wait-actions button', has_text='Not waiting').click(); await pg.wait_for_timeout(600)
        check('clearing removes it from the Waiting tab', tree()[first['id']]['waiting_on'] is None and await pg.locator('#view .node').count() == 0 and 'Nothing is waiting' in await pg.locator('#view').text_content())
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(600)
        check('Ctrl+Z brings the waiting mark back', tree()[first['id']]['waiting_on'] == 'Sam: which channel')
        await pg.click('#tabs button[data-view=all]'); await pg.wait_for_timeout(300)
        await pg.locator(f'.node[data-id="{first["id"]}"] > .row').hover()
        await pg.locator(f'.node[data-id="{first["id"]}"] > .row > .menu').click(); await pg.wait_for_timeout(200)
        check('menu shows bump + clear when waiting', await pg.locator('#popover .menu-list button', has_text='Bump').count() == 1)
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(100)
        # --- notes (description under the title)
        await pg.locator(f'.node[data-id="{first["id"]}"] > .row > .text').click()
        await pg.keyboard.press('Control+.'); await pg.wait_for_timeout(200)
        check('Ctrl+. opens the note editor focused', await pg.evaluate('document.activeElement.className') == 'note-text')
        await pg.keyboard.type('bob@example.com'); await pg.keyboard.press('Enter'); await pg.keyboard.type('ask about the deadline'); await pg.wait_for_timeout(700)
        check('note saved with its line break', tree()[first['id']]['note'] == 'bob@example.com\nask about the deadline', tree()[first['id']]['note'])
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(200)
        pv = pg.locator(f'.node[data-id="{first["id"]}"] > .row > .note-preview')
        check('Esc collapses to a grey first-line preview', await pg.locator(f'.node[data-id="{first["id"]}"] > .note').count() == 0 and await pv.text_content() == 'bob@example.com')
        check('focus returns to the title', await pg.evaluate('document.activeElement.className') == 'text')
        await pg.reload(); await pg.wait_for_selector('.node'); await pg.wait_for_timeout(200)
        check('preview survives a reload', await pv.text_content() == 'bob@example.com')
        await pv.click(); await pg.wait_for_timeout(200)
        check('clicking the preview expands the full note', 'ask about the deadline' in await pg.locator(f'.node[data-id="{first["id"]}"] > .note > .note-text').text_content())
        await pg.keyboard.press('Control+End'); await pg.keyboard.type(' and budget'); await pg.wait_for_timeout(700)
        check('typing in the editor saves', tree()[first['id']]['note'].endswith('deadline and budget'))
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(700)
        check('Ctrl+Z in the note undoes the note edit', tree()[first['id']]['note'] == 'bob@example.com\nask about the deadline', tree()[first['id']]['note'])
        await pg.keyboard.press('Control+End'); await pg.keyboard.press('Enter')
        if os.environ.get('BROWSER', 'chromium') == 'firefox':
            await pg.evaluate("() => insertPasted(document.activeElement, 'https://docs.google.com/sheet/attendants')")
        else:
            await pg.evaluate("""() => { const el = document.activeElement; const dt = new DataTransfer(); dt.setData('text/plain', 'https://docs.google.com/sheet/attendants');
              el.dispatchEvent(new ClipboardEvent('paste', { clipboardData: dt, bubbles: true, cancelable: true })); }""")
        await pg.wait_for_timeout(700)
        check('a url pasted into a note is a link at once', await pg.locator(f'.node[data-id="{first["id"]}"] > .note > .note-text a.link').count() == 1)
        check('and the note keeps its lines', tree()[first['id']]['note'] == 'bob@example.com\nask about the deadline\nhttps://docs.google.com/sheet/attendants', tree()[first['id']]['note'])
        await pg.keyboard.type(' (edit)'); await pg.wait_for_timeout(700)
        check('typing after a note link works', tree()[first['id']]['note'].endswith('attendants (edit)'), tree()[first['id']]['note'])
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(200)
        check('preview shows the first line', await pg.locator(f'.node[data-id="{first["id"]}"] > .row > .note-preview').text_content() == 'bob@example.com')
        await pg.fill('#search', 'about the deadline'); await pg.wait_for_timeout(400)
        check('search finds text inside notes', await pg.locator(f'.node[data-id="{first["id"]}"]').count() == 1 and await pg.locator('#view .node.task').count() <= 3, await pg.locator('#view .node.task').count())
        await pg.fill('#search', ''); await pg.wait_for_timeout(400)
        await pg.locator(f'.node[data-id="{first["id"]}"] > .row').hover()
        await pg.locator(f'.node[data-id="{first["id"]}"] > .row > .menu').click(); await pg.wait_for_timeout(200)
        check('menu offers Show note when a note exists', await pg.locator('#popover .menu-list button', has_text='Show note').count() == 1)
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(100)
        # --- delete from a selected row (no need to empty the text first)
        tgt = by_text(tree(), 'Jordan reachout')
        await pg.locator(f'.node[data-id="{tgt["id"]}"] > .row').click(position={'x': 4, 'y': 6})  # the row itself, not the words
        check('clicking the row marks it current', 'current' in (await pg.locator(f'.node[data-id="{tgt["id"]}"]').get_attribute('class')))
        await pg.keyboard.press('Delete'); await pg.wait_for_timeout(600)
        check('Delete on a selected row archives it', tgt['id'] not in tree())
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(600)
        check('Ctrl+Z restores it', tgt['id'] in tree())
        await pg.locator(f'.node[data-id="{tgt["id"]}"] > .row > .text').click()
        await pg.keyboard.press('Control+Shift+Backspace'); await pg.wait_for_timeout(600)
        check('Ctrl+Shift+Backspace while typing archives it', tgt['id'] not in tree())
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(600)
        check('and Ctrl+Z restores it again', tgt['id'] in tree())
        # --- links: paste a url over highlighted words
        lk = by_text(tree(), 'Slack repost')
        await pg.locator(f'.node[data-id="{lk["id"]}"] > .row > .text').click()
        await pg.keyboard.press('End'); await pg.keyboard.press('Shift+Home')
        if os.environ.get('BROWSER', 'chromium') == 'firefox':  # firefox hides data on synthetic clipboard events; call the paste logic directly
            await pg.evaluate("() => insertPasted(document.activeElement, 'https://example.com/attendants')")
        else:
            await pg.evaluate("""() => { const el = document.activeElement; const dt = new DataTransfer(); dt.setData('text/plain', 'https://example.com/attendants');
              el.dispatchEvent(new ClipboardEvent('paste', { clipboardData: dt, bubbles: true, cancelable: true })); }""")
        await pg.wait_for_timeout(700)
        check('pasting a url over highlighted words makes a link', tree()[lk['id']]['text'] == '[Slack repost](https://example.com/attendants)', tree()[lk['id']]['text'])
        check('link renders as an anchor', await pg.locator(f'.node[data-id="{lk["id"]}"] > .row > .text a.link').get_attribute('href') == 'https://example.com/attendants')
        await pg.keyboard.type(' now'); await pg.wait_for_timeout(600)
        check('typing after the link keeps it', tree()[lk['id']]['text'] == '[Slack repost](https://example.com/attendants) now', tree()[lk['id']]['text'])
        await pg.screenshot(path=f'{SP}/ui-link.png')
        await pg.reload(); await pg.wait_for_selector('.node'); await pg.wait_for_timeout(200)
        check('link survives a reload', await pg.locator(f'.node[data-id="{lk["id"]}"] > .row > .text a.link').count() == 1)
        await pg.locator(f'.node[data-id="{lk["id"]}"] > .row > .text').click(); await pg.keyboard.press('End'); await pg.keyboard.press('Enter'); await pg.wait_for_timeout(600)
        check('Enter after a link splits cleanly', tree()[lk['id']]['text'] == '[Slack repost](https://example.com/attendants) now', tree()[lk['id']]['text'])
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(600)
        tl = pg.locator(f'.node[data-id="{lk["id"]}"] > .row > .text'); tb = await tl.bounding_box()
        await tl.click(position={'x': tb['width'] - 2, 'y': tb['height'] / 2}); await pg.keyboard.press('End'); await pg.keyboard.type(' see ')  # past the link, at the end of the words
        await pg.evaluate("() => insertPasted(document.activeElement, 'https://example.com/x')"); await pg.wait_for_timeout(700)
        check('a url pasted with nothing selected links itself', tree()[lk['id']]['text'].endswith(' see https://example.com/x') and await pg.locator(f'.node[data-id="{lk["id"]}"] > .row > .text a.link').count() == 2, tree()[lk['id']]['text'])
        # --- light / dark toggle
        bg0 = await pg.evaluate('getComputedStyle(document.body).backgroundColor')
        await pg.click('#theme'); await pg.wait_for_timeout(500)
        bg1 = await pg.evaluate('getComputedStyle(document.body).backgroundColor')
        check('theme toggle changes the page colours', bg0 != bg1 and await pg.evaluate('document.documentElement.dataset.theme') in ('light', 'dark'), (bg0, bg1))
        await pg.reload(); await pg.wait_for_selector('.node')
        check('theme choice survives a reload', await pg.evaluate('getComputedStyle(document.body).backgroundColor') == bg1)
        await pg.click('#theme'); await pg.wait_for_timeout(500)
        check('toggling back restores the colours', await pg.evaluate('getComputedStyle(document.body).backgroundColor') == bg0)
        # --- tab shortcut, item shortcuts outside the title, multi-select
        await pg.keyboard.press('Alt+Shift+ArrowRight'); await pg.wait_for_timeout(300)
        check('Alt+Shift+→ moves to the next tab', await pg.locator('#tabs button.active').get_attribute('data-view') == 'today')
        await pg.keyboard.press('Alt+Shift+ArrowLeft'); await pg.wait_for_timeout(300)
        check('Alt+Shift+← comes back', await pg.locator('#tabs button.active').get_attribute('data-view') == 'all')
        w1 = by_text(tree(), 'Jordan reachout')
        await pg.locator(f'.node[data-id="{w1["id"]}"] > .row > .text').click(); await pg.keyboard.press('Control+.'); await pg.wait_for_timeout(200)
        await pg.keyboard.press('Control+b'); await pg.wait_for_timeout(200)
        check('Ctrl+B works from the note editor', await pg.locator('#popover .wait-picker').count() == 1)
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(100)
        await pg.locator(f'.node[data-id="{w1["id"]}"] > .row').click(position={'x': 4, 'y': 6})
        await pg.keyboard.press('Control+b'); await pg.wait_for_timeout(200)
        check('Ctrl+B works from a selected row', await pg.locator('#popover .wait-picker').count() == 1)
        await pg.keyboard.press('Escape'); await pg.wait_for_timeout(100)
        sa = by_text(tree(), 'Reach out jo bell'); sb = w1
        await pg.locator(f'.node[data-id="{sa["id"]}"] > .row').click(position={'x': 4, 'y': 6})
        await pg.locator(f'.node[data-id="{sb["id"]}"] > .row').click(position={'x': 4, 'y': 6}, modifiers=['Shift'])
        check('Shift+click selects a range', await pg.locator('#view .node.selected').count() == 2)
        await pg.keyboard.press('Enter'); await pg.wait_for_timeout(800)
        check('Enter marks the selection done', bool(tree()[sa['id']]['done_at'] and tree()[sb['id']]['done_at']))
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(800)
        check('one Ctrl+Z reopens both', not tree()[sa['id']]['done_at'] and not tree()[sb['id']]['done_at'])
        check('selection survives the refresh', await pg.locator('#view .node.selected').count() == 2)
        dst = by_text(tree(), 'ICRA 27 proposal add pics')  # a nearby row: dropping on its lower half puts the selection right after it
        await pg.drag_and_drop(f'.node[data-id="{sa["id"]}"] > .row > .handle', f'.node[data-id="{dst["id"]}"] > .row', target_position={'x': 200, 'y': rh - 4}); await pg.wait_for_timeout(800)
        t2 = tree(); check('dragging one handle moves the whole selection', t2[sa['id']]['parent_id'] == dst['parent_id'] and t2[sb['id']]['parent_id'] == dst['parent_id'] and sorted([t2[sa['id']]['position'], t2[sb['id']]['position']]) == [t2[dst['id']]['position'] + 1, t2[dst['id']]['position'] + 2] and t2[sb['id']]['position'] < t2[sa['id']]['position'], (t2[sa['id']]['parent_id'], t2[sb['id']]['parent_id'], dst['parent_id']))
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(800)
        check('one Ctrl+Z moves both back', tree()[sa['id']]['parent_id'] == sa['parent_id'] and tree()[sb['id']]['parent_id'] == sb['parent_id'])
        await pg.keyboard.press('Delete'); await pg.wait_for_timeout(800)
        check('Delete archives the selection', sa['id'] not in tree() and sb['id'] not in tree())
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(1000)
        check('one Ctrl+Z restores both', sa['id'] in tree() and sb['id'] in tree())
        await pg.keyboard.press('Escape')
        # --- due soon → red; Today switch
        plain = by_text(tree(), 'PhD Apps think through')
        api_patch = lambda nid, body: urllib.request.urlopen(urllib.request.Request(URL + f'api/nodes/{nid}', data=json.dumps(body).encode(), method='PATCH', headers={'Content-Type': 'application/json'})).read()
        import datetime as _dt
        api_patch(plain['id'], {'due_date': (_dt.date.today() + _dt.timedelta(days=1)).isoformat()})
        await pg.reload(); await pg.wait_for_selector('.node'); await pg.wait_for_timeout(300)
        check('due tomorrow tags the task red', tree()[plain['id']]['priority'] == 'urgent' and (await pg.locator(f'.node[data-id="{plain["id"]}"]').get_attribute('data-prio')) == 'urgent')
        await pg.locator(f'.node[data-id="{plain["id"]}"] > .row > .text').click(); await pg.keyboard.press('Control+Shift+Digit3'); await pg.wait_for_timeout(600)
        await pg.reload(); await pg.wait_for_selector('.node'); await pg.wait_for_timeout(300)
        check('a colour picked afterwards sticks', tree()[plain['id']]['priority'] == 'normal')
        await pg.click('#tabs button[data-view=today]'); await pg.wait_for_timeout(400)
        check('Today opens on Due today', 'Due today' in await pg.locator('.view-switch button.on').text_content())
        await pg.locator('.view-switch button', has_text='Everything else').click(); await pg.wait_for_timeout(400)
        check('Everything else lists open tasks that are not due', await pg.locator(f'.node[data-id="{plain["id"]}"]').count() == 1 and await pg.locator('#view .node.task:not(.ctx)').count() > 5, await pg.locator('#view .node.task:not(.ctx)').count())  # due tomorrow but no longer red → not 'due today'
        await pg.locator('.view-switch button', has_text='Due today').click(); await pg.wait_for_timeout(300)
        await pg.click('#tabs button[data-view=all]'); await pg.wait_for_timeout(300)
        # --- insights
        await pg.click('#tabs button[data-view=insights]'); await pg.wait_for_timeout(1200)
        check('Insights shows the stat row and a year heatmap', await pg.locator('.stats .stat').count() == 4 and await pg.locator('.heat .cell').count() == 365, await pg.locator('.heat .cell').count())
        check('Insights draws the charts', await pg.locator('svg.chart').count() >= 5, await pg.locator('svg.chart').count())
        await pg.locator('.viz-range button', has_text='Year').click(); await pg.wait_for_timeout(900)
        check('Year range folds completions into weeks', await pg.locator('.viz h3', has_text='Completed per week').count() == 1)
        await pg.locator('.viz-table-btn').first.click(); await pg.wait_for_timeout(200)
        check('charts have a table twin', await pg.locator('.viz-table:not([hidden]) table tr').count() > 10)
        await pg.locator('.heat .cell').last.click(); await pg.wait_for_timeout(1200)
        check("picking a day shows that day's list, read-only", await pg.locator('#past .past-tree .node').count() > 50 and await pg.locator('#past .text[contenteditable="false"]').count() > 50 and 'open task' in await pg.locator('#past .past-summary').text_content())
        before = tree()
        await pg.locator('#past .node .text').first.click(); await pg.keyboard.type('zzz'); await pg.wait_for_timeout(500)
        check('the past list cannot be edited', not any('zzz' in n['text'] for n in tree().values()))
        check('trying to edit shows a read-only message', 'Read-only' in await pg.locator('#toast').text_content())
        await pg.keyboard.press('Delete'); await pg.keyboard.press('Enter'); await pg.keyboard.press('Control+Enter'); await pg.wait_for_timeout(600)
        pchk = pg.locator('#past .node.task > .row > .check').first
        await pchk.click(); await pg.wait_for_timeout(600)
        after = tree()
        check('Delete / Enter / ticking in the past list touch nothing live', set(after) == set(before) and all(after[k]['done_at'] == before[k]['done_at'] and after[k]['text'] == before[k]['text'] for k in before))
        check('the past checkbox stays as it was', await pchk.is_checked() == bool(next(n for n in json.load(urllib.request.urlopen(URL + 'api/snapshot/' + __import__('datetime').date.today().isoformat()))['nodes'] if n['kind'] == 'task')['done_at']))
        check('the tab row ends with Insights; History stays out of it', [await b.text_content() for b in await pg.locator('#tabs button:visible').all()][-1].startswith('Insights'))
        await pg.locator('.ins-foot a').click(); await pg.wait_for_timeout(500)
        check('History opens from the Insights footer', await pg.locator('table.history').count() == 1)
        await pg.click('#tabs button[data-view=all]'); await pg.wait_for_timeout(300)
        # --- clicking the paper lets go of everything
        bg = by_text(tree(), 'Jordan reachout')
        await pg.locator(f'.node[data-id="{bg["id"]}"] > .row').click(position={'x': 4, 'y': 6})
        check('a clicked row is picked', await pg.locator('#view .node.current').count() == 1 and await pg.locator('#view .node.selected').count() == 0)
        await pg.mouse.click(5, 400)  # the page margin, left of the outline
        await pg.wait_for_timeout(150)
        check('clicking the paper clears the highlight and selection', await pg.locator('#view .node.current, #view .node.selected').count() == 0 and await pg.evaluate('S.current') is None)
        # --- priority filter
        await pg.click('#filter-btn'); await pg.wait_for_timeout(200)
        await pg.locator('#popover .filter-list label', has_text='Urgent').click(); await pg.wait_for_timeout(400)
        urgent = [n for n in tree().values() if n['kind'] == 'task' and n['priority'] == 'urgent' and not n['color']]
        shown = await pg.locator('#view .node.task:not(.ctx)').count()
        check('filtering on Urgent shows only urgent tasks', shown == len(urgent) and shown > 0, (shown, len(urgent)))
        check('the Filter button says it is active', 'on' in (await pg.locator('#filter-btn').get_attribute('class') or ''))
        await pg.locator('#popover .filter-list button', has_text='Clear').click(); await pg.wait_for_timeout(400)
        check('clearing the filter shows everything again', await pg.locator('#view .node').count() > 100)
        await pg.keyboard.press('Escape')
        # --- priority / colour on a whole selection
        pa = by_text(tree(), 'ICRA 27 proposal add pics'); pb = by_text(tree(), 'Competition Layout Send')
        await pg.locator(f'.node[data-id="{pa["id"]}"] > .row').click(position={'x': 4, 'y': 6})
        await pg.locator(f'.node[data-id="{pb["id"]}"] > .row').click(position={'x': 4, 'y': 6}, modifiers=['Shift'])
        await pg.locator(f'.node[data-id="{pa["id"]}"] > .row > .dot').click(); await pg.wait_for_timeout(200)
        check('clicking a control of a selected row keeps the selection', await pg.locator('#view .node.selected').count() >= 2)
        await pg.locator('#popover .swatch[data-prio=later]').click(); await pg.wait_for_timeout(700)
        t3 = tree(); check('a priority picked on one selected row applies to all of them', t3[pa['id']]['priority'] == 'later' and t3[pb['id']]['priority'] == 'later')
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(700)
        t4 = tree(); check('one Ctrl+Z reverts the whole batch', t4[pa['id']]['priority'] == 'urgent' and t4[pb['id']]['priority'] == 'urgent')
        await pg.keyboard.press('Escape')
        # --- auto-sort
        sec = by_text(tree(), 'Racer - Conf 2026')
        order_of = lambda: [n['id'] for n in sorted((x for x in tree().values() if x['parent_id'] == sec['id']), key=lambda x: x['position'])]
        rank = lambda x: (1 if x['done_at'] else 0, {'urgent': 0, 'soon': 1, 'normal': 2, 'later': 3, 'none': 5}[x['priority']] if not (x['color'] and x['priority'] == 'none') else 4)
        before_order = order_of()
        await pg.click('#sort-btn'); await pg.wait_for_timeout(900)
        kids = [tree()[i] for i in order_of()]; ranks = [rank(x) for x in kids if x['kind'] == 'task']
        check('switching Auto-sort on orders the section by urgency', ranks == sorted(ranks) and len(ranks) > 3 and 'on' in (await pg.locator('#sort-btn').get_attribute('class') or ''), ranks)
        low = [x for x in kids if x['kind'] == 'task' and x['priority'] != 'urgent' and not x['done_at']][-1]  # the last open non-urgent task: making it urgent must move it up
        await pg.locator(f'.node[data-id="{low["id"]}"] > .row > .text').click(); await pg.keyboard.press('Control+Shift+Digit1'); await pg.wait_for_timeout(2300)  # the change shows first, the glide follows a second later
        kids2 = [tree()[i] for i in order_of()]
        check('making a task urgent moves it up on its own', tree()[low['id']]['priority'] == 'urgent' and [x['id'] for x in kids2 if x['kind'] == 'task'].index(low['id']) < [x['id'] for x in kids if x['kind'] == 'task'].index(low['id']))
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(1000)
        check('one Ctrl+Z undoes the priority and the re-sort together', tree()[low['id']]['priority'] == low['priority'] and [x['id'] for x in [tree()[i] for i in order_of()]] == [x['id'] for x in kids])
        await pg.click('#sort-btn'); await pg.wait_for_timeout(300)
        check('Auto-sort switches off', 'on' not in (await pg.locator('#sort-btn').get_attribute('class') or ''))
        await pg.keyboard.press('Control+z'); await pg.wait_for_timeout(900)
        check('and the first sort can be undone too', order_of() == before_order)
        # --- mobile viewport sanity
        await pg.set_viewport_size({'width': 390, 'height': 800}); await pg.wait_for_timeout(300)
        check('no horizontal scroll on phone width', await pg.evaluate('document.documentElement.scrollWidth <= window.innerWidth + 1'))
        await pg.screenshot(path=f'{SP}/ui-phone.png')
        await b.close()
        print('\n'.join(l for l in logs if not l.startswith('log: API patch')))
        print('\nconsole errors:', len(errors)); [print('  ', e[:200]) for e in errors[:15]]
        print('first history row:', str(first)[:120] if first else None)
        fails = [n for n, ok in checks if not ok]
        print(f'\n{len(checks) - len(fails)}/{len(checks)} checks passed'); 
        if fails: print('FAILED:', fails)
asyncio.run(main())
